dist: xenial
language: haskell
ghc:
- 8.2
- 8.4
- 8.6
env:
- TRAVIS_BUILD_CABAL_DEFAULT=2.4
install:
- cabal new-configure --enable-tests --write-ghc-environment-files=always
- cabal new-build --only-dependencies --enable-tests
script:
- cabal new-build --enable-tests
- cabal new-test
- cabal new-haddock
- cabal new-sdist
- cabal check
