#!/bin/bash
# Computes the paths to files causing changes to the ghci flags. You probably won’t be running this yourself, but rather ghcide will via configuration in hie.yaml.

set -e

cd $(dirname "$0")/..

echo "cabal.project"

echo "fused-effects.cabal"
